---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zomato
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zomato
  template:
    metadata:
      labels:
        app: zomato
    spec:
      containers:
      - name: zomato
        image: gouthamkumarsai/zomato:latest
        ports:
        - containerPort: 3000   # App runs on 3000 inside container

---
apiVersion: v1
kind: Service
metadata:
  name: zomato-service
spec:
  selector:
    app: zomato
  ports:
  - protocol: TCP
    port: 7080              # Service port (clients use this)
    targetPort: 3000        # Forward to container’s 3000
  type: LoadBalancer         # Kind will map to a random NodePort
