name: CI/CD Pipeline

on:
  push:
    branches:
      - main   # adjust if your branch is different

jobs:
  build-and-deploy:
    runs-on: self-hosted   # since you’re using GitHub runner on your local

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # SonarQube Scan
      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          docker run --rm \
            -e SONAR_HOST_URL="http://localhost:9000" \
            -e SONAR_LOGIN=$SONAR_TOKEN \
            -v "${{ github.workspace }}:/usr/src" \
            sonarsource/sonar-scanner-cli

      # Build Docker Image
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/zomato:latest .

      # Push to DockerHub
      - name: Push Docker Image
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/zomato:latest

      # Trivy Scan
      - name: Trivy Scan
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy:latest image ${{ secrets.DOCKERHUB_USERNAME }}/zomato:latest

      # Deploy to Kind
      - name: Deploy to Kind
        run: |
          kubectl apply -f deployment-service.yml
          kubectl rollout status deployment/zomato
