name: build and analyze, scan 
on:
  push:
    branches:
      - main 

jobs:
  build-analyze-scan:
    name: build
    runs-on: [self-hosted]
    steps:
      - name: checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Building Code and analyze with sonarqube
        uses: actions/checkout@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - name: dependencies install
        run:  nmp install
      - name: trivy FS scan
        run: trivy fs . > trivy-report.txt
      - name: docker build push
        run:
          docker build -t zomato .
          docker tag zomato gouthamkumarsai/zomato:latest1
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p {{ secrets.DOCKER_TOKEN }}      
          docker push gouthamkumarsai/zomato:latest1
        env:
          DOCKER_CLI_ACL: 1 
        
  deploy:            
    needs: build-analyze-scan
    runs-on: [self-hosted]
    steps: 
      - name: docker pull
        run: docker pull gouthamkumarsai/zomato:latest1
      - name: Image Scan 
        run: trivy image gouthamkumarsai/zomato:latest1
      - name: docker run container 
        run: docker run -itd -p 3000:3000 --name zomato gouthamkumarsai/zomato:latest1    
           
