name: CI/CD with Kind

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted   # since you're using local GitHub runner with Kind
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      # Install Node.js dependencies before docker build
      - name: Install dependencies
        run: |
          npm install

      # Build docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/zomato:latest .

      # Login to Docker Hub
      - name: Docker login
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      # Push image
      - name: Push image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/zomato:latest

      # Apply Kubernetes deployment
      - name: Deploy to Kind cluster
        run: |
          kubectl apply -f deployment-service.yml
